// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AgentRunStatus.
const (
	AgentRunStatusCancelled   AgentRunStatus = "cancelled"
	AgentRunStatusCompleted   AgentRunStatus = "completed"
	AgentRunStatusFailed      AgentRunStatus = "failed"
	AgentRunStatusInterrupted AgentRunStatus = "interrupted"
	AgentRunStatusPending     AgentRunStatus = "pending"
	AgentRunStatusRunning     AgentRunStatus = "running"
)

// Valid indicates whether the value is a known member of the AgentRunStatus enum.
func (e AgentRunStatus) Valid() bool {
	switch e {
	case AgentRunStatusCancelled:
		return true
	case AgentRunStatusCompleted:
		return true
	case AgentRunStatusFailed:
		return true
	case AgentRunStatusInterrupted:
		return true
	case AgentRunStatusPending:
		return true
	case AgentRunStatusRunning:
		return true
	default:
		return false
	}
}

// Defines values for AgentRunStepStatus.
const (
	AgentRunStepStatusCompleted   AgentRunStepStatus = "completed"
	AgentRunStepStatusFailed      AgentRunStepStatus = "failed"
	AgentRunStepStatusInterrupted AgentRunStepStatus = "interrupted"
	AgentRunStepStatusPending     AgentRunStepStatus = "pending"
	AgentRunStepStatusRunning     AgentRunStepStatus = "running"
)

// Valid indicates whether the value is a known member of the AgentRunStepStatus enum.
func (e AgentRunStepStatus) Valid() bool {
	switch e {
	case AgentRunStepStatusCompleted:
		return true
	case AgentRunStepStatusFailed:
		return true
	case AgentRunStepStatusInterrupted:
		return true
	case AgentRunStepStatusPending:
		return true
	case AgentRunStepStatusRunning:
		return true
	default:
		return false
	}
}

// Defines values for AgentRunStepType.
const (
	AgentRunStepTypeLlm  AgentRunStepType = "llm"
	AgentRunStepTypeTool AgentRunStepType = "tool"
)

// Valid indicates whether the value is a known member of the AgentRunStepType enum.
func (e AgentRunStepType) Valid() bool {
	switch e {
	case AgentRunStepTypeLlm:
		return true
	case AgentRunStepTypeTool:
		return true
	default:
		return false
	}
}

// Defines values for DocumentStatus.
const (
	DocumentStatusFailed     DocumentStatus = "failed"
	DocumentStatusProcessing DocumentStatus = "processing"
	DocumentStatusQueued     DocumentStatus = "queued"
	DocumentStatusReady      DocumentStatus = "ready"
)

// Valid indicates whether the value is a known member of the DocumentStatus enum.
func (e DocumentStatus) Valid() bool {
	switch e {
	case DocumentStatusFailed:
		return true
	case DocumentStatusProcessing:
		return true
	case DocumentStatusQueued:
		return true
	case DocumentStatusReady:
		return true
	default:
		return false
	}
}

// Defines values for MessageRole.
const (
	MessageRoleAssistant MessageRole = "assistant"
	MessageRoleSystem    MessageRole = "system"
	MessageRoleTool      MessageRole = "tool"
	MessageRoleUser      MessageRole = "user"
)

// Valid indicates whether the value is a known member of the MessageRole enum.
func (e MessageRole) Valid() bool {
	switch e {
	case MessageRoleAssistant:
		return true
	case MessageRoleSystem:
		return true
	case MessageRoleTool:
		return true
	case MessageRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for MessageStatus.
const (
	MessageStatusCompleted MessageStatus = "completed"
	MessageStatusFailed    MessageStatus = "failed"
	MessageStatusStreaming MessageStatus = "streaming"
)

// Valid indicates whether the value is a known member of the MessageStatus enum.
func (e MessageStatus) Valid() bool {
	switch e {
	case MessageStatusCompleted:
		return true
	case MessageStatusFailed:
		return true
	case MessageStatusStreaming:
		return true
	default:
		return false
	}
}

// Defines values for ModelSummaryKind.
const (
	ModelSummaryKindChat      ModelSummaryKind = "chat"
	ModelSummaryKindEmbedding ModelSummaryKind = "embedding"
)

// Valid indicates whether the value is a known member of the ModelSummaryKind enum.
func (e ModelSummaryKind) Valid() bool {
	switch e {
	case ModelSummaryKindChat:
		return true
	case ModelSummaryKindEmbedding:
		return true
	default:
		return false
	}
}

// Defines values for ToolCatalogEntrySideEffectLevel.
const (
	READONLY           ToolCatalogEntrySideEffectLevel = "READ_ONLY"
	WRITEIDEMPOTENT    ToolCatalogEntrySideEffectLevel = "WRITE_IDEMPOTENT"
	WRITENONIDEMPOTENT ToolCatalogEntrySideEffectLevel = "WRITE_NON_IDEMPOTENT"
)

// Valid indicates whether the value is a known member of the ToolCatalogEntrySideEffectLevel enum.
func (e ToolCatalogEntrySideEffectLevel) Valid() bool {
	switch e {
	case READONLY:
		return true
	case WRITEIDEMPOTENT:
		return true
	case WRITENONIDEMPOTENT:
		return true
	default:
		return false
	}
}

// Defines values for UsageByModelKind.
const (
	UsageByModelKindChat      UsageByModelKind = "chat"
	UsageByModelKindEmbedding UsageByModelKind = "embedding"
)

// Valid indicates whether the value is a known member of the UsageByModelKind enum.
func (e UsageByModelKind) Valid() bool {
	switch e {
	case UsageByModelKindChat:
		return true
	case UsageByModelKindEmbedding:
		return true
	default:
		return false
	}
}

// Agent defines model for Agent.
type Agent struct {
	CreatedAt   time.Time          `json:"createdAt"`
	Description string             `json:"description"`
	Id          openapi_types.UUID `json:"id"`

	// Instruction 系统提示词
	Instruction string `json:"instruction"`
	Name        string `json:"name"`

	// ToolNames 这个 Agent 被允许使用的工具名子集（见 ToolCatalogEntry.name）
	ToolNames []string  `json:"toolNames"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// AgentRun defines model for AgentRun.
type AgentRun struct {
	AgentId     openapi_types.UUID `json:"agentId"`
	CreatedAt   time.Time          `json:"createdAt"`
	CurrentStep int                `json:"currentStep"`
	Id          openapi_types.UUID `json:"id"`
	Input       string             `json:"input"`
	Output      string             `json:"output"`
	Status      AgentRunStatus     `json:"status"`
	UpdatedAt   time.Time          `json:"updatedAt"`
}

// AgentRunStatus defines model for AgentRun.Status.
type AgentRunStatus string

// AgentRunPage defines model for AgentRunPage.
type AgentRunPage struct {
	Items []AgentRun `json:"items"`

	// NextCursor 下一页的游标；null 表示没有更多了。
	NextCursor *string `json:"nextCursor,omitempty"`
}

// AgentRunStep defines model for AgentRunStep.
type AgentRunStep struct {
	CreatedAt time.Time          `json:"createdAt"`
	Error     *string            `json:"error,omitempty"`
	Id        openapi_types.UUID `json:"id"`
	LatencyMs *int               `json:"latencyMs,omitempty"`
	RunId     openapi_types.UUID `json:"runId"`
	Seq       int                `json:"seq"`
	Status    AgentRunStepStatus `json:"status"`

	// ToolArgs 原始 JSON，形状由具体工具决定，前端不需要强类型解析
	ToolArgs   interface{}      `json:"toolArgs,omitempty"`
	ToolName   *string          `json:"toolName,omitempty"`
	ToolResult interface{}      `json:"toolResult,omitempty"`
	Type       AgentRunStepType `json:"type"`
}

// AgentRunStepStatus defines model for AgentRunStep.Status.
type AgentRunStepStatus string

// AgentRunStepType defines model for AgentRunStep.Type.
type AgentRunStepType string

// Capabilities 模型声明支持的能力，全部由用户手动勾选——OpenAI 兼容 API
// 不保证能自动查询这些（技术方案 §五）。embedding 这一位不在这里：
// 它由服务端根据这个模型是 chatModel 还是 embeddingModel 自动决定，
// 不需要用户勾选。
type Capabilities struct {
	Chat        *bool `json:"chat,omitempty"`
	Reasoning   *bool `json:"reasoning,omitempty"`
	Streaming   *bool `json:"streaming,omitempty"`
	ToolCalling *bool `json:"toolCalling,omitempty"`
}

// ChatModelInput defines model for ChatModelInput.
type ChatModelInput struct {
	// Capabilities 模型声明支持的能力，全部由用户手动勾选——OpenAI 兼容 API
	// 不保证能自动查询这些（技术方案 §五）。embedding 这一位不在这里：
	// 它由服务端根据这个模型是 chatModel 还是 embeddingModel 自动决定，
	// 不需要用户勾选。
	Capabilities *Capabilities `json:"capabilities,omitempty"`

	// ContextWindow Example: 32000
	ContextWindow int `json:"contextWindow"`

	// MaxOutputTokens Example: 4096
	MaxOutputTokens int `json:"maxOutputTokens"`

	// ModelId Example: Qwen/Qwen2.5-7B-Instruct
	ModelId string `json:"modelId"`

	// TokenizerType Example: cl100k_base
	TokenizerType string `json:"tokenizerType"`
}

// Conversation defines model for Conversation.
type Conversation struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`

	// KnowledgeBaseId 可选关联的知识库——关联了，发消息时会做检索增强；
	// 不关联就是一次不带 RAG 的纯对话。方案文档没有定义这个字段，
	// 是实现时补上的决策（见 internal/conversation/model.go 的注释）。
	KnowledgeBaseId *openapi_types.UUID `json:"knowledgeBaseId,omitempty"`
	Title           string              `json:"title"`
	UpdatedAt       time.Time           `json:"updatedAt"`
}

// ConversationPage defines model for ConversationPage.
type ConversationPage struct {
	Items []Conversation `json:"items"`

	// NextCursor 下一页的游标；null 表示没有更多了。
	NextCursor *string `json:"nextCursor,omitempty"`
}

// CreateAgentRequest defines model for CreateAgentRequest.
type CreateAgentRequest struct {
	Description *string `json:"description,omitempty"`

	// Instruction Example: 你是一个帮助用户做算术和资料检索的助手。
	Instruction *string `json:"instruction,omitempty"`

	// Name Example: 计算助手
	Name string `json:"name"`

	// ToolNames Example: ["calculator"]
	ToolNames *[]string `json:"toolNames,omitempty"`
}

// CreateConversationRequest defines model for CreateConversationRequest.
type CreateConversationRequest struct {
	KnowledgeBaseId *openapi_types.UUID `json:"knowledgeBaseId,omitempty"`

	// Title Example: 关于 ConGoRAG 的问答
	Title *string `json:"title,omitempty"`
}

// CreateKnowledgeBaseRequest defines model for CreateKnowledgeBaseRequest.
type CreateKnowledgeBaseRequest struct {
	// Name Example: 我的知识库
	Name string `json:"name"`
}

// CreateProviderRequest defines model for CreateProviderRequest.
type CreateProviderRequest struct {
	// AllowEmbeddingReset 用户已经确认"换 embedding 模型会清空已有向量、并自动重建"。
	//
	// 默认 false：库里的向量不属于这个模型、或者改列类型会清空已有
	// 向量时，保存失败并返回 409 `embedding_change_requires_reindex`，
	// 不做任何修改。前端据此弹确认框，用户点了确认再带 true 重发一次。
	//
	// true：在同一个事务里清空这些向量、改列类型，并把全部文档重新
	// 排队重建；重建完成的文档数在响应的 requeuedDocuments 里。
	AllowEmbeddingReset *bool `json:"allowEmbeddingReset,omitempty"`

	// ApiKey 落盘前用应用级主密钥加密，明文只在这一次请求体里出现
	ApiKey string `json:"apiKey"`

	// BaseUrl Example: https://api.siliconflow.cn/v1
	BaseUrl   string         `json:"baseUrl"`
	ChatModel ChatModelInput `json:"chatModel"`

	// EmbeddingModelId 只要模型名——维度不用填，服务端用这个字段连同 baseUrl/apiKey
	// 发一次真实的 embedding 请求探测出来。
	//
	//
	// Example: BAAI/bge-m3
	EmbeddingModelId string `json:"embeddingModelId"`
}

// Document defines model for Document.
type Document struct {
	ByteSize int64 `json:"byteSize"`

	// ChunkCount 这份文档当前的向量分块数（issue #82）。
	//
	// 【为什么它是"检索质量的第一个可观察量"】切分策略不合适时分块数
	// 会明显异常（一份 10 页的 PDF 切出 3 块、或者切出 8000 块）。
	// 它也是"文档到底处理完没有"的第二个信号：status 是 ready 但
	// chunkCount 是 0，说明切分或向量化那一轮实际上什么都没产出。
	//
	// 未处理完的文档是 0——不是 null。null 会让前端多写一条分支，
	// 而"还没有分块"和"没有这个字段"对用户是同一件事。
	ChunkCount int64     `json:"chunkCount"`
	CreatedAt  time.Time `json:"createdAt"`

	// Filename 用户上传时的原始文件名
	Filename        string             `json:"filename"`
	Id              openapi_types.UUID `json:"id"`
	KnowledgeBaseId openapi_types.UUID `json:"knowledgeBaseId"`

	// Status 四态状态机（代码架构设计 §5.4）：queued → processing → ready，
	// 任意阶段失败进 failed，failed 只能退回 queued 重试。
	Status    DocumentStatus `json:"status"`
	UpdatedAt time.Time      `json:"updatedAt"`
}

// DocumentStatus 四态状态机（代码架构设计 §5.4）：queued → processing → ready，
// 任意阶段失败进 failed，failed 只能退回 queued 重试。
type DocumentStatus string

// DocumentPage defines model for DocumentPage.
type DocumentPage struct {
	Items []Document `json:"items"`

	// NextCursor 下一页的游标；null 表示没有更多了。
	NextCursor *string `json:"nextCursor,omitempty"`
}

// KnowledgeBase defines model for KnowledgeBase.
type KnowledgeBase struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	UpdatedAt time.Time          `json:"updatedAt"`
}

// KnowledgeSearchHit defines model for KnowledgeSearchHit.
type KnowledgeSearchHit struct {
	ChunkId    openapi_types.UUID `json:"chunkId"`
	DocumentId openapi_types.UUID `json:"documentId"`

	// Filename 这个分块来自哪份文档（检索 SQL 里 JOIN documents 拿到）
	Filename string `json:"filename"`

	// Score 余弦相似度，越大越相关
	Score float64 `json:"score"`

	// Snippet 分块正文
	Snippet string `json:"snippet"`
}

// KnowledgeSearchRequest Example: {"query":"ConGoRAG 的向量检索用的是什么类型？","topK":5}
type KnowledgeSearchRequest struct {
	// Query 要检索的文本。会先被当前生效的 embedding 模型变成向量。
	Query string `json:"query"`

	// TopK 最多返回多少个命中分块。省略时用 5。
	//
	// 【越界返回 400，不静默夹取】夹取会让人以为"只命中这么多"，
	// 而实际是被服务端截断了——调试视图上这个区别很关键。
	TopK *int `json:"topK,omitempty"`
}

// KnowledgeSearchResult defines model for KnowledgeSearchResult.
type KnowledgeSearchResult struct {
	// Hits 按相似度从高到低。可能是空数组（这个知识库没有任何向量，
	// 或者 query 与所有分块都不相关）——空数组与"检索失败"是两件事，
	// 前者前端应显示"没有命中"，后者是一个 4xx/5xx。
	Hits []KnowledgeSearchHit `json:"hits"`
}

// Message defines model for Message.
type Message struct {
	Content        string             `json:"content"`
	ConversationId openapi_types.UUID `json:"conversationId"`
	CreatedAt      time.Time          `json:"createdAt"`
	Id             openapi_types.UUID `json:"id"`
	Role           MessageRole        `json:"role"`
	SequenceNo     int64              `json:"sequenceNo"`
	Status         MessageStatus      `json:"status"`
}

// MessageRole defines model for Message.Role.
type MessageRole string

// MessageStatus defines model for Message.Status.
type MessageStatus string

// MessagePage defines model for MessagePage.
type MessagePage struct {
	Items []Message `json:"items"`

	// NextCursor 下一页的游标；null 表示没有更早的消息了。
	//
	// **方向是「更旧」**：会话消息的第一页给的是**最新**的 N 条
	// （按 sequence_no 升序返回），翻下一页拿的是更早的。聊天页
	// 打开就该看到最近发生的事，而不是一年前的那一句。
	NextCursor *string `json:"nextCursor,omitempty"`
}

// ModelSummary defines model for ModelSummary.
type ModelSummary struct {
	// Capabilities 模型声明支持的能力，全部由用户手动勾选——OpenAI 兼容 API
	// 不保证能自动查询这些（技术方案 §五）。embedding 这一位不在这里：
	// 它由服务端根据这个模型是 chatModel 还是 embeddingModel 自动决定，
	// 不需要用户勾选。
	Capabilities  Capabilities `json:"capabilities"`
	ContextWindow int          `json:"contextWindow"`
	CreatedAt     time.Time    `json:"createdAt"`

	// EmbeddingDim 只对 kind = embedding 有意义；chat 模型这一位恒为 0
	EmbeddingDim    int                `json:"embeddingDim"`
	Id              openapi_types.UUID `json:"id"`
	Kind            ModelSummaryKind   `json:"kind"`
	MaxOutputTokens int                `json:"maxOutputTokens"`
	ModelId         string             `json:"modelId"`
	TokenizerType   string             `json:"tokenizerType"`
}

// ModelSummaryKind defines model for ModelSummary.Kind.
type ModelSummaryKind string

// Problem defines model for Problem.
type Problem struct {
	// Detail 具体说明
	//
	// Example: knowledge base 3f2b1c... not found
	Detail *string `json:"detail,omitempty"`

	// Status Example: 404
	Status int `json:"status"`

	// Title 人类可读的简短说明
	//
	// Example: 资源不存在
	Title *string `json:"title,omitempty"`

	// Type 机器可读的错误类型，前端按它分支
	//
	// Example: not_found
	Type string `json:"type"`
}

// ProviderWithModels defines model for ProviderWithModels.
type ProviderWithModels struct {
	BaseUrl   string             `json:"baseUrl"`
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	Models    []ModelSummary     `json:"models"`

	// RequeuedDocuments 这一次真的被重新排队的文档数。只有 POST /providers 在确实执行了
	// 重建时才是一个数字；GET /providers 恒为 null——它描述的是"这一次
	// 请求做了什么"，不是一个可以持久化的状态。
	RequeuedDocuments *int `json:"requeuedDocuments,omitempty"`
}

// ReindexAccepted defines model for ReindexAccepted.
type ReindexAccepted struct {
	// Enqueued 本次真的排进队列的文档数。已经在排队或正在处理的文档不计入——
	// 它们本来就会被重新处理一遍。
	Enqueued int `json:"enqueued"`
}

// RenameKnowledgeBaseRequest defines model for RenameKnowledgeBaseRequest.
type RenameKnowledgeBaseRequest struct {
	// Name Example: 新的名字
	Name string `json:"name"`
}

// SendMessageRequest defines model for SendMessageRequest.
type SendMessageRequest struct {
	// Text Example: ConGoRAG 的默认端口是多少？
	Text string `json:"text"`
}

// StartAgentRunRequest defines model for StartAgentRunRequest.
type StartAgentRunRequest struct {
	// Input Example: 3 个 128 的和乘以 2 是多少？
	Input string `json:"input"`
}

// ToolCatalogEntry defines model for ToolCatalogEntry.
type ToolCatalogEntry struct {
	Description     string                          `json:"description"`
	Name            string                          `json:"name"`
	SideEffectLevel ToolCatalogEntrySideEffectLevel `json:"sideEffectLevel"`
}

// ToolCatalogEntrySideEffectLevel defines model for ToolCatalogEntry.SideEffectLevel.
type ToolCatalogEntrySideEffectLevel string

// UsageByModel defines model for UsageByModel.
type UsageByModel struct {
	// Calls 调用次数。**哪怕上游没回 usage 也会计一次**（那一行的 token 记 0）
	// ——行数代表调用次数，是可观测事实。
	Calls            int64            `json:"calls"`
	CompletionTokens int64            `json:"completionTokens"`
	Kind             UsageByModelKind `json:"kind"`

	// ModelId llm_models 的主键
	ModelId openapi_types.UUID `json:"modelId"`

	// ModelName 用户在引导页里敲的那个模型名（llm_models.model_id）。
	// 给用户看的是它，不是上面那个 uuid。
	ModelName    string             `json:"modelName"`
	PromptTokens int64              `json:"promptTokens"`
	ProviderId   openapi_types.UUID `json:"providerId"`
}

// UsageByModelKind defines model for UsageByModel.Kind.
type UsageByModelKind string

// UsageSummary defines model for UsageSummary.
type UsageSummary struct {
	ByModel               []UsageByModel `json:"byModel"`
	TotalCompletionTokens int64          `json:"totalCompletionTokens"`
	TotalPromptTokens     int64          `json:"totalPromptTokens"`
}

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int

// Conflict defines model for Conflict.
type Conflict = Problem

// EmbeddingChangeRequiresReindex defines model for EmbeddingChangeRequiresReindex.
type EmbeddingChangeRequiresReindex = Problem

// InternalError defines model for InternalError.
type InternalError = Problem

// InvalidArgument defines model for InvalidArgument.
type InvalidArgument = Problem

// NotFound defines model for NotFound.
type NotFound = Problem

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = Problem

// ListAgentRunsParams defines parameters for ListAgentRuns.
type ListAgentRunsParams struct {
	// Limit 一页最多返回多少条。省略时用 50；允许 1..200，越界返回 400
	// （不静默夹取——那会让你以为拿满了，实际少了一半）。
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor 上一页响应里 nextCursor 的值，用来取下一页。第一页省略它。
	//
	// **不透明**：不要解析它的内容、也不要自己构造。它的格式（目前是
	// base64）随时可能变，按内容分支的客户端会在某次升级后静默拿到
	// 错的一页。解不出来时服务端返回 400。
	//
	// 方向：nextCursor 的含义是「更旧的一页」（这三个列表都是按时间
	// 倒序、或按消息序号往回翻），不是「第 N+1 页」。
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// StartAgentRunParams defines parameters for StartAgentRun.
type StartAgentRunParams struct {
	// IdempotencyKey 客户端生成的去重键。同一个 Agent 上带同一个键重复提交时，
	// 服务端不重新执行这次运行，而是把该 run 已记录的事件补发出来
	// （首帧仍是 run_started，带的是原来那条 run 的 id）。
	//
	// 省略这个头时行为与没有幂等能力时完全一样（每次都真正执行）。
	// 同一个键配不同的 input 会返回 invalid_argument 的错误帧，
	// 而不是把上一次运行的结果重放一遍。
	//
	// 保留窗口与会话消息那条路径共用同一个值（24 小时，见
	// docs/adr/008-idempotency-replay-window.md）。过期之后同一个键
	// 可以重新执行——这是有意的产品语义，不是缺陷。
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// ListConversationsParams defines parameters for ListConversations.
type ListConversationsParams struct {
	// Limit 一页最多返回多少条。省略时用 50；允许 1..200，越界返回 400
	// （不静默夹取——那会让你以为拿满了，实际少了一半）。
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor 上一页响应里 nextCursor 的值，用来取下一页。第一页省略它。
	//
	// **不透明**：不要解析它的内容、也不要自己构造。它的格式（目前是
	// base64）随时可能变，按内容分支的客户端会在某次升级后静默拿到
	// 错的一页。解不出来时服务端返回 400。
	//
	// 方向：nextCursor 的含义是「更旧的一页」（这三个列表都是按时间
	// 倒序、或按消息序号往回翻），不是「第 N+1 页」。
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// SubscribeConversationEventsParams defines parameters for SubscribeConversationEvents.
type SubscribeConversationEventsParams struct {
	// AfterEventId 只返回这个 id 之后的事件；省略或传 0 表示从头开始
	AfterEventId *int64 `form:"after_event_id,omitempty" json:"after_event_id,omitempty"`
}

// ListConversationMessagesParams defines parameters for ListConversationMessages.
type ListConversationMessagesParams struct {
	// Limit 一页最多返回多少条。省略时用 50；允许 1..200，越界返回 400
	// （不静默夹取——那会让你以为拿满了，实际少了一半）。
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor 上一页响应里 nextCursor 的值，用来取下一页。第一页省略它。
	//
	// **不透明**：不要解析它的内容、也不要自己构造。它的格式（目前是
	// base64）随时可能变，按内容分支的客户端会在某次升级后静默拿到
	// 错的一页。解不出来时服务端返回 400。
	//
	// 方向：nextCursor 的含义是「更旧的一页」（这三个列表都是按时间
	// 倒序、或按消息序号往回翻），不是「第 N+1 页」。
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// SendMessageParams defines parameters for SendMessage.
type SendMessageParams struct {
	// IdempotencyKey 客户端生成的去重键。同一个会话里带同一个键重复提交时，
	// 服务端不重新执行生成，而是把该轮已记录的事件补发出来，
	// 并以该轮的 done / error 帧收尾。
	//
	// 省略这个头时行为与没有幂等能力时完全一样（每次都重新生成）。
	// 同一个键配不同的正文会返回 invalid_argument 的错误帧，
	// 而不是把上一轮的回答重放一遍。
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// ListDocumentsParams defines parameters for ListDocuments.
type ListDocumentsParams struct {
	// Limit 一页最多返回多少条。省略时用 50；允许 1..200，越界返回 400
	// （不静默夹取——那会让你以为拿满了，实际少了一半）。
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor 上一页响应里 nextCursor 的值，用来取下一页。第一页省略它。
	//
	// **不透明**：不要解析它的内容、也不要自己构造。它的格式（目前是
	// base64）随时可能变，按内容分支的客户端会在某次升级后静默拿到
	// 错的一页。解不出来时服务端返回 400。
	//
	// 方向：nextCursor 的含义是「更旧的一页」（这三个列表都是按时间
	// 倒序、或按消息序号往回翻），不是「第 N+1 页」。
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// UploadDocumentMultipartBody defines parameters for UploadDocument.
type UploadDocumentMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// SubscribeRunEventsParams defines parameters for SubscribeRunEvents.
type SubscribeRunEventsParams struct {
	// AfterEventId 只补发 event_id 严格大于它的那些事件。
	AfterEventId *int64 `form:"after_event_id,omitempty" json:"after_event_id,omitempty"`
}

// GetUsageSummaryParams defines parameters for GetUsageSummary.
type GetUsageSummaryParams struct {
	// Since 起始时间（含）。RFC3339 格式。省略表示不限。
	Since *time.Time `form:"since,omitempty" json:"since,omitempty"`

	// Until 结束时间（不含）。RFC3339 格式。省略表示不限。
	Until *time.Time `form:"until,omitempty" json:"until,omitempty"`
}

// CreateAgentJSONRequestBody defines body for CreateAgent for application/json ContentType.
type CreateAgentJSONRequestBody = CreateAgentRequest

// StartAgentRunJSONRequestBody defines body for StartAgentRun for application/json ContentType.
type StartAgentRunJSONRequestBody = StartAgentRunRequest

// CreateConversationJSONRequestBody defines body for CreateConversation for application/json ContentType.
type CreateConversationJSONRequestBody = CreateConversationRequest

// SendMessageJSONRequestBody defines body for SendMessage for application/json ContentType.
type SendMessageJSONRequestBody = SendMessageRequest

// CreateKnowledgeBaseJSONRequestBody defines body for CreateKnowledgeBase for application/json ContentType.
type CreateKnowledgeBaseJSONRequestBody = CreateKnowledgeBaseRequest

// RenameKnowledgeBaseJSONRequestBody defines body for RenameKnowledgeBase for application/json ContentType.
type RenameKnowledgeBaseJSONRequestBody = RenameKnowledgeBaseRequest

// UploadDocumentMultipartRequestBody defines body for UploadDocument for multipart/form-data ContentType.
type UploadDocumentMultipartRequestBody UploadDocumentMultipartBody

// SearchKnowledgeBaseJSONRequestBody defines body for SearchKnowledgeBase for application/json ContentType.
type SearchKnowledgeBaseJSONRequestBody = KnowledgeSearchRequest

// CreateProviderJSONRequestBody defines body for CreateProvider for application/json ContentType.
type CreateProviderJSONRequestBody = CreateProviderRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListAgents 列出已创建的 Agent
	// (GET /api/v1/agents)
	ListAgents(c *gin.Context)
	// CreateAgent 创建一个 Agent
	// (POST /api/v1/agents)
	CreateAgent(c *gin.Context)
	// GetAgent 查一个 Agent 的配置
	// (GET /api/v1/agents/{id})
	GetAgent(c *gin.Context, id openapi_types.UUID)
	// ListAgentRuns 列出一个 Agent 的历史执行记录（按创建时间倒序，keyset 分页）
	// (GET /api/v1/agents/{id}/runs)
	ListAgentRuns(c *gin.Context, id openapi_types.UUID, params ListAgentRunsParams)
	// StartAgentRun 启动一次 Agent 执行，响应是 SSE 流（text/event-stream）——
	// 和 sendMessage 同一个模式,帧格式见 docs/sse-protocol.md。
	//
	// **流的首帧永远是 `run_started`**（data: {"runId": ...}），
	// 新建与命中幂等键重放两种情况都会发。取消、run 级重订阅、
	// 跳转到运行详情都要用这个 id，而此前五种事件里没有任何一种带它。
	//
	// 带 Idempotency-Key 重复提交时不会重新执行：服务端把那条 run
	// 已记录的事件补发一遍（同样的 event 类型、同样的真实 event_id）。
	// 作用的范围是「同一个 Agent + 同一个键」，键保留 24 小时。
	// (POST /api/v1/agents/{id}/runs)
	StartAgentRun(c *gin.Context, id openapi_types.UUID, params StartAgentRunParams)
	// ListConversations 列出会话（keyset 分页），按**最近活动时间**倒序。
	//
	// 【为什么排序键不是 createdAt】这个列表的用处是"回到刚才那个会话"，
	// 而一个三天前建的会话可能刚刚才被用过。按创建时间排会让它沉到列表
	// 底部，用户每次都得往下翻——列表的意义正好没了。
	//
	// 【形状与另外三个列表一致】items + nextCursor，不是裸数组
	// （v3.0 把三个列表端点统一成了这个形状，新端点跟着走，
	// 否则会出现两种列表形状并存）。
	// (GET /api/v1/conversations)
	ListConversations(c *gin.Context, params ListConversationsParams)
	// CreateConversation 新建一个会话
	// (POST /api/v1/conversations)
	CreateConversation(c *gin.Context)
	// SubscribeConversationEvents 断线续传入口（SSE），docs/sse-protocol.md「断线续传」一节
	// (GET /api/v1/conversations/{id}/events)
	SubscribeConversationEvents(c *gin.Context, id openapi_types.UUID, params SubscribeConversationEventsParams)
	// ListConversationMessages 列出一个会话的消息（按 sequence_no 升序，keyset 分页，第一页给最新的）
	// (GET /api/v1/conversations/{id}/messages)
	ListConversationMessages(c *gin.Context, id openapi_types.UUID, params ListConversationMessagesParams)
	// SendMessage 发一条消息，响应是 SSE 流（text/event-stream），不是普通 JSON。
	// 帧格式和事件类型见 docs/sse-protocol.md，那份文档是唯一权威来源，
	// 这里的 schema 只是占位（OpenAPI 对流式响应体的描述能力有限）。
	//
	// 带 Idempotency-Key 重复提交时不会重新生成：服务端把那一轮已经
	// 产生的事件补发一遍（同样的 event 类型、同样的真实 event_id），
	// 所以客户端不需要为「重发」写第二套解析逻辑。
	//
	// 补发的作用域是「同一个会话 + 同一个键」。键保留 24 小时，过期之后
	// 同一个键可以重新执行。
	// (POST /api/v1/conversations/{id}/messages)
	SendMessage(c *gin.Context, id openapi_types.UUID, params SendMessageParams)
	// DeleteDocument 删除一份文档（连带它的分块；磁盘文件异步清理）
	// (DELETE /api/v1/documents/{id})
	DeleteDocument(c *gin.Context, id openapi_types.UUID)
	// GetDocument 查一份文档的当前状态（前端拿它做处理中的轮询）
	// (GET /api/v1/documents/{id})
	GetDocument(c *gin.Context, id openapi_types.UUID)
	// ReindexDocument 重新索引一份文档（重新切分、向量化、入库）
	// (POST /api/v1/documents/{id}/reindex)
	ReindexDocument(c *gin.Context, id openapi_types.UUID)
	// ListKnowledgeBases 列出全部知识库（按创建时间倒序）
	// (GET /api/v1/knowledge-bases)
	ListKnowledgeBases(c *gin.Context)
	// CreateKnowledgeBase 新建一个知识库
	// (POST /api/v1/knowledge-bases)
	CreateKnowledgeBase(c *gin.Context)
	// DeleteKnowledgeBase 删除知识库（连带它的文档和分块）
	// (DELETE /api/v1/knowledge-bases/{id})
	DeleteKnowledgeBase(c *gin.Context, id openapi_types.UUID)
	// GetKnowledgeBase 取一个知识库
	// (GET /api/v1/knowledge-bases/{id})
	GetKnowledgeBase(c *gin.Context, id openapi_types.UUID)
	// RenameKnowledgeBase 改知识库的名字
	// (PATCH /api/v1/knowledge-bases/{id})
	RenameKnowledgeBase(c *gin.Context, id openapi_types.UUID)
	// ListDocuments 列出这个知识库下的文档（按创建时间倒序，keyset 分页）
	// (GET /api/v1/knowledge-bases/{id}/documents)
	ListDocuments(c *gin.Context, id openapi_types.UUID, params ListDocumentsParams)
	// UploadDocument 上传一个文档（异步处理：落盘 + 入队，立即返回）
	// (POST /api/v1/knowledge-bases/{id}/documents)
	UploadDocument(c *gin.Context, id openapi_types.UUID)
	// ReindexKnowledgeBase 重新索引一个知识库下的全部文档
	// (POST /api/v1/knowledge-bases/{id}/reindex)
	ReindexKnowledgeBase(c *gin.Context, id openapi_types.UUID)
	// SearchKnowledgeBase 在指定知识库里做一次向量检索，返回命中的分块与相似度
	// (POST /api/v1/knowledge-bases/{id}/search)
	SearchKnowledgeBase(c *gin.Context, id openapi_types.UUID)
	// ListProviders 列出已配置的模型接入（Key 不会出现在响应里）
	// (GET /api/v1/providers)
	ListProviders(c *gin.Context)
	// CreateProvider 保存一个模型接入配置（引导页"保存并开始"）
	// (POST /api/v1/providers)
	CreateProvider(c *gin.Context)
	// CancelAgentRun 取消一次在途的 Agent 运行。
	//
	// 取消后 run 的状态是 `cancelled`（不是 `failed`）——两者对用户的含义
	// 完全不同：前者是他自己要求的，后者是出错了。已经跑到终态的 run
	// 不可取消（409 conflict），没跑完的那一步保持 `interrupted`
	// （取消发生在 run 层，step 没有 cancelled 这一态）。
	//
	// 响应里带的是**取消生效之后**的状态，不是取消前的快照。
	// (POST /api/v1/runs/{runId}/cancel)
	CancelAgentRun(c *gin.Context, runId openapi_types.UUID)
	// SubscribeRunEvents 补发一条 run 已经记录的事件（run 维度的断线重订阅）。
	//
	// **补发完已有的历史就结束响应**，不持有连接等新事件——与会话维度那条
	// GET /conversations/{id}/events 是同一条语义。要看后续内容就再连一次。
	//
	// `after_event_id` 省略时从 0 开始，也就是把这条 run 的事件从头补发
	// 一遍（run 的事件号从 1 开始，按 run 独立发号）。
	// (GET /api/v1/runs/{runId}/events)
	SubscribeRunEvents(c *gin.Context, runId openapi_types.UUID, params SubscribeRunEventsParams)
	// ResumeAgentRun 从断点恢复一次被中断的运行（第二步起）。响应是 SSE 流，
	// 首帧同样是 run_started。
	//
	// **先检查再开流**：所有拒绝理由都在这条请求变成流之前判掉，
	// 所以下面那三种 409 是正常的 Problem 响应，而不是流里的一帧——
	// 客户端能按 type 给出准确的下一步提示。
	//
	// 拒绝的三种情况：
	//   - `conflict`：只有 interrupted 的 run 可以恢复（别的状态要么已经
	//     结束、要么正在跑）。
	//   - `state_schema_version_mismatch`：这条 run 的快照是旧版本的代码
	//     写的，结构已经不兼容——明确拒绝并提示重新发起，而不是硬解出
	//     一个半截状态。
	//   - `tool_effect_already_applied` / `replay_unsafe`：没跑完的那一步
	//     不允许被平台自动重放（副作用可能已经生效，或工具自己声明了
	//     不可重放）。方案 §8 的恢复边界明说了不保证这类工具被安全重放。
	//
	// (POST /api/v1/runs/{runId}/resume)
	ResumeAgentRun(c *gin.Context, runId openapi_types.UUID)
	// ListRunSteps 列出一次执行的全部步骤（执行轨迹页用）
	// (GET /api/v1/runs/{runId}/steps)
	ListRunSteps(c *gin.Context, runId openapi_types.UUID)
	// ListToolCatalog 列出可用工具目录（创建 Agent 表单的勾选列表用）
	// (GET /api/v1/tools)
	ListToolCatalog(c *gin.Context)
	// GetUsageSummary 按模型聚合的 token 用量
	// (GET /api/v1/usage)
	GetUsageSummary(c *gin.Context, params GetUsageSummaryParams)
	// Healthz 存活探针
	// (GET /healthz)
	Healthz(c *gin.Context)
	// Readyz 就绪探针（探测数据库）
	// (GET /readyz)
	Readyz(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListAgents operation middleware
func (siw *ServerInterfaceWrapper) ListAgents(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListAgents(c)
}

// CreateAgent operation middleware
func (siw *ServerInterfaceWrapper) CreateAgent(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateAgent(c)
}

// GetAgent operation middleware
func (siw *ServerInterfaceWrapper) GetAgent(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAgent(c, id)
}

// ListAgentRuns operation middleware
func (siw *ServerInterfaceWrapper) ListAgentRuns(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAgentRunsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", c.Request.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursor: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListAgentRuns(c, id, params)
}

// StartAgentRun operation middleware
func (siw *ServerInterfaceWrapper) StartAgentRun(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params StartAgentRunParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Idempotency-Key, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Idempotency-Key: %w", err), http.StatusBadRequest)
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartAgentRun(c, id, params)
}

// ListConversations operation middleware
func (siw *ServerInterfaceWrapper) ListConversations(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListConversationsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", c.Request.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursor: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListConversations(c, params)
}

// CreateConversation operation middleware
func (siw *ServerInterfaceWrapper) CreateConversation(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateConversation(c)
}

// SubscribeConversationEvents operation middleware
func (siw *ServerInterfaceWrapper) SubscribeConversationEvents(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params SubscribeConversationEventsParams

	// ------------- Optional query parameter "after_event_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "after_event_id", c.Request.URL.Query(), &params.AfterEventId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter after_event_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SubscribeConversationEvents(c, id, params)
}

// ListConversationMessages operation middleware
func (siw *ServerInterfaceWrapper) ListConversationMessages(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListConversationMessagesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", c.Request.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursor: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListConversationMessages(c, id, params)
}

// SendMessage operation middleware
func (siw *ServerInterfaceWrapper) SendMessage(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params SendMessageParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Idempotency-Key, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Idempotency-Key: %w", err), http.StatusBadRequest)
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SendMessage(c, id, params)
}

// DeleteDocument operation middleware
func (siw *ServerInterfaceWrapper) DeleteDocument(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteDocument(c, id)
}

// GetDocument operation middleware
func (siw *ServerInterfaceWrapper) GetDocument(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDocument(c, id)
}

// ReindexDocument operation middleware
func (siw *ServerInterfaceWrapper) ReindexDocument(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ReindexDocument(c, id)
}

// ListKnowledgeBases operation middleware
func (siw *ServerInterfaceWrapper) ListKnowledgeBases(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListKnowledgeBases(c)
}

// CreateKnowledgeBase operation middleware
func (siw *ServerInterfaceWrapper) CreateKnowledgeBase(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateKnowledgeBase(c)
}

// DeleteKnowledgeBase operation middleware
func (siw *ServerInterfaceWrapper) DeleteKnowledgeBase(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteKnowledgeBase(c, id)
}

// GetKnowledgeBase operation middleware
func (siw *ServerInterfaceWrapper) GetKnowledgeBase(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetKnowledgeBase(c, id)
}

// RenameKnowledgeBase operation middleware
func (siw *ServerInterfaceWrapper) RenameKnowledgeBase(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RenameKnowledgeBase(c, id)
}

// ListDocuments operation middleware
func (siw *ServerInterfaceWrapper) ListDocuments(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDocumentsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", c.Request.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursor: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListDocuments(c, id, params)
}

// UploadDocument operation middleware
func (siw *ServerInterfaceWrapper) UploadDocument(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UploadDocument(c, id)
}

// ReindexKnowledgeBase operation middleware
func (siw *ServerInterfaceWrapper) ReindexKnowledgeBase(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ReindexKnowledgeBase(c, id)
}

// SearchKnowledgeBase operation middleware
func (siw *ServerInterfaceWrapper) SearchKnowledgeBase(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SearchKnowledgeBase(c, id)
}

// ListProviders operation middleware
func (siw *ServerInterfaceWrapper) ListProviders(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListProviders(c)
}

// CreateProvider operation middleware
func (siw *ServerInterfaceWrapper) CreateProvider(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateProvider(c)
}

// CancelAgentRun operation middleware
func (siw *ServerInterfaceWrapper) CancelAgentRun(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "runId" -------------
	var runId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "runId", c.Param("runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter runId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CancelAgentRun(c, runId)
}

// SubscribeRunEvents operation middleware
func (siw *ServerInterfaceWrapper) SubscribeRunEvents(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "runId" -------------
	var runId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "runId", c.Param("runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter runId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params SubscribeRunEventsParams

	// ------------- Optional query parameter "after_event_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "after_event_id", c.Request.URL.Query(), &params.AfterEventId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter after_event_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SubscribeRunEvents(c, runId, params)
}

// ResumeAgentRun operation middleware
func (siw *ServerInterfaceWrapper) ResumeAgentRun(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "runId" -------------
	var runId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "runId", c.Param("runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter runId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ResumeAgentRun(c, runId)
}

// ListRunSteps operation middleware
func (siw *ServerInterfaceWrapper) ListRunSteps(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "runId" -------------
	var runId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "runId", c.Param("runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter runId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListRunSteps(c, runId)
}

// ListToolCatalog operation middleware
func (siw *ServerInterfaceWrapper) ListToolCatalog(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListToolCatalog(c)
}

// GetUsageSummary operation middleware
func (siw *ServerInterfaceWrapper) GetUsageSummary(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsageSummaryParams

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "since", c.Request.URL.Query(), &params.Since, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter since: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "until" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "until", c.Request.URL.Query(), &params.Until, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter until: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsageSummary(c, params)
}

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Healthz(c)
}

// Readyz operation middleware
func (siw *ServerInterfaceWrapper) Readyz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Readyz(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.Healthz)
	router.GET(options.BaseURL+"/readyz", wrapper.Readyz)
	router.GET(options.BaseURL+"/api/v1/knowledge-bases", wrapper.ListKnowledgeBases)
	router.POST(options.BaseURL+"/api/v1/knowledge-bases", wrapper.CreateKnowledgeBase)
	router.DELETE(options.BaseURL+"/api/v1/knowledge-bases/:id", wrapper.DeleteKnowledgeBase)
	router.GET(options.BaseURL+"/api/v1/knowledge-bases/:id", wrapper.GetKnowledgeBase)
	router.PATCH(options.BaseURL+"/api/v1/knowledge-bases/:id", wrapper.RenameKnowledgeBase)
	router.GET(options.BaseURL+"/api/v1/knowledge-bases/:id/documents", wrapper.ListDocuments)
	router.POST(options.BaseURL+"/api/v1/knowledge-bases/:id/documents", wrapper.UploadDocument)
	router.POST(options.BaseURL+"/api/v1/knowledge-bases/:id/reindex", wrapper.ReindexKnowledgeBase)
	router.POST(options.BaseURL+"/api/v1/knowledge-bases/:id/search", wrapper.SearchKnowledgeBase)
	router.DELETE(options.BaseURL+"/api/v1/documents/:id", wrapper.DeleteDocument)
	router.GET(options.BaseURL+"/api/v1/documents/:id", wrapper.GetDocument)
	router.POST(options.BaseURL+"/api/v1/documents/:id/reindex", wrapper.ReindexDocument)
	router.GET(options.BaseURL+"/api/v1/conversations", wrapper.ListConversations)
	router.POST(options.BaseURL+"/api/v1/conversations", wrapper.CreateConversation)
	router.GET(options.BaseURL+"/api/v1/conversations/:id/messages", wrapper.ListConversationMessages)
	router.POST(options.BaseURL+"/api/v1/conversations/:id/messages", wrapper.SendMessage)
	router.GET(options.BaseURL+"/api/v1/conversations/:id/events", wrapper.SubscribeConversationEvents)
	router.GET(options.BaseURL+"/api/v1/providers", wrapper.ListProviders)
	router.POST(options.BaseURL+"/api/v1/providers", wrapper.CreateProvider)
	router.GET(options.BaseURL+"/api/v1/usage", wrapper.GetUsageSummary)
	router.GET(options.BaseURL+"/api/v1/tools", wrapper.ListToolCatalog)
	router.GET(options.BaseURL+"/api/v1/agents", wrapper.ListAgents)
	router.POST(options.BaseURL+"/api/v1/agents", wrapper.CreateAgent)
	router.GET(options.BaseURL+"/api/v1/agents/:id", wrapper.GetAgent)
	router.GET(options.BaseURL+"/api/v1/agents/:id/runs", wrapper.ListAgentRuns)
	router.POST(options.BaseURL+"/api/v1/agents/:id/runs", wrapper.StartAgentRun)
	router.GET(options.BaseURL+"/api/v1/runs/:runId/events", wrapper.SubscribeRunEvents)
	router.POST(options.BaseURL+"/api/v1/runs/:runId/cancel", wrapper.CancelAgentRun)
	router.POST(options.BaseURL+"/api/v1/runs/:runId/resume", wrapper.ResumeAgentRun)
	router.GET(options.BaseURL+"/api/v1/runs/:runId/steps", wrapper.ListRunSteps)
}
