/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 存活探针 */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-bases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出全部知识库（按创建时间倒序） */
        get: operations["listKnowledgeBases"];
        put?: never;
        /** 新建一个知识库 */
        post: operations["createKnowledgeBase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-bases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 取一个知识库 */
        get: operations["getKnowledgeBase"];
        put?: never;
        post?: never;
        /** 删除知识库（连带它的文档和分块） */
        delete: operations["deleteKnowledgeBase"];
        options?: never;
        head?: never;
        /** 改知识库的名字 */
        patch: operations["renameKnowledgeBase"];
        trace?: never;
    };
    "/api/v1/knowledge-bases/{id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 列出这个知识库下的全部文档 */
        get: operations["listDocuments"];
        put?: never;
        /** 上传一个文档（异步处理：落盘 + 入队，立即返回） */
        post: operations["uploadDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 查一份文档的当前状态（前端拿它做处理中的轮询） */
        get: operations["getDocument"];
        put?: never;
        post?: never;
        /** 删除一份文档（连带它的分块；磁盘文件异步清理） */
        delete: operations["deleteDocument"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 新建一个会话 */
        post: operations["createConversation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 按顺序列出一个会话的全部消息（前端刷新页面重载历史用） */
        get: operations["listConversationMessages"];
        put?: never;
        /**
         * 发一条消息，响应是 SSE 流（text/event-stream），不是普通 JSON。
         *     帧格式和事件类型见 docs/sse-protocol.md，那份文档是唯一权威来源，
         *     这里的 schema 只是占位（OpenAPI 对流式响应体的描述能力有限）。
         */
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 断线续传入口（SSE），docs/sse-protocol.md「断线续传」一节 */
        get: operations["subscribeConversationEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出已配置的模型接入（Key 不会出现在响应里） */
        get: operations["listProviders"];
        put?: never;
        /** 保存一个模型接入配置（引导页"保存并开始"） */
        post: operations["createProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出可用工具目录（创建 Agent 表单的勾选列表用） */
        get: operations["listToolCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出已创建的 Agent */
        get: operations["listAgents"];
        put?: never;
        /** 创建一个 Agent */
        post: operations["createAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 查一个 Agent 的配置 */
        get: operations["getAgent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 列出一个 Agent 的历史执行记录 */
        get: operations["listAgentRuns"];
        put?: never;
        /**
         * 启动一次 Agent 执行，响应是 SSE 流（text/event-stream）——
         *     和 sendMessage 同一个模式,帧格式见 docs/sse-protocol.md。
         *     这一轮没有 run 维度的断线重订阅（M4-B 才做),这次连接就是
         *     唯一能实时看到过程的机会,执行记录本身（agent_runs/
         *     agent_run_steps）落库后可以事后通过 GET .../runs/{runId}/steps 查。
         */
        post: operations["startAgentRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{runId}/steps": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        /** 列出一次执行的全部步骤（执行轨迹页用） */
        get: operations["listRunSteps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        KnowledgeBase: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Conversation: {
            /** Format: uuid */
            id: string;
            title: string;
            /**
             * Format: uuid
             * @description 可选关联的知识库——关联了，发消息时会做检索增强；
             *     不关联就是一次不带 RAG 的纯对话。方案文档没有定义这个字段，
             *     是实现时补上的决策（见 internal/conversation/model.go 的注释）。
             */
            knowledgeBaseId?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateConversationRequest: {
            /** @example 关于 ConGoRAG 的问答 */
            title?: string;
            /** Format: uuid */
            knowledgeBaseId?: string | null;
        };
        SendMessageRequest: {
            /** @example ConGoRAG 的默认端口是多少？ */
            text: string;
        };
        Message: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            conversationId: string;
            /** @enum {string} */
            role: "system" | "user" | "assistant" | "tool";
            content: string;
            /** @enum {string} */
            status: "streaming" | "completed" | "failed";
            /** Format: int64 */
            sequenceNo: number;
            /** Format: date-time */
            createdAt: string;
        };
        Document: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            knowledgeBaseId: string;
            /** @description 用户上传时的原始文件名 */
            filename: string;
            /**
             * @description 四态状态机（代码架构设计 §5.4）：queued → processing → ready，
             *     任意阶段失败进 failed，failed 只能退回 queued 重试。
             * @enum {string}
             */
            status: "queued" | "processing" | "ready" | "failed";
            /** Format: int64 */
            byteSize: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateKnowledgeBaseRequest: {
            /** @example 我的知识库 */
            name: string;
        };
        RenameKnowledgeBaseRequest: {
            /** @example 新的名字 */
            name: string;
        };
        /**
         * @description 模型声明支持的能力，全部由用户手动勾选——OpenAI 兼容 API
         *     不保证能自动查询这些（技术方案 §五）。embedding 这一位不在这里：
         *     它由服务端根据这个模型是 chatModel 还是 embeddingModel 自动决定，
         *     不需要用户勾选。
         */
        Capabilities: {
            /** @default true */
            chat: boolean;
            /** @default false */
            streaming: boolean;
            /** @default false */
            toolCalling: boolean;
            /** @default false */
            reasoning: boolean;
        };
        ChatModelInput: {
            /** @example Qwen/Qwen2.5-7B-Instruct */
            modelId: string;
            capabilities?: components["schemas"]["Capabilities"];
            /** @example 32000 */
            contextWindow: number;
            /** @example 4096 */
            maxOutputTokens: number;
            /** @example cl100k_base */
            tokenizerType: string;
        };
        CreateProviderRequest: {
            /** @example https://api.siliconflow.cn/v1 */
            baseUrl: string;
            /** @description 落盘前用应用级主密钥加密，明文只在这一次请求体里出现 */
            apiKey: string;
            chatModel: components["schemas"]["ChatModelInput"];
            /**
             * @description 只要模型名——维度不用填，服务端用这个字段连同 baseUrl/apiKey
             *     发一次真实的 embedding 请求探测出来。
             * @example BAAI/bge-m3
             */
            embeddingModelId: string;
        };
        ModelSummary: {
            /** Format: uuid */
            id: string;
            modelId: string;
            /** @enum {string} */
            kind: "chat" | "embedding";
            capabilities: components["schemas"]["Capabilities"];
            contextWindow: number;
            maxOutputTokens: number;
            tokenizerType: string;
            /** @description 只对 kind = embedding 有意义；chat 模型这一位恒为 0 */
            embeddingDim: number;
            /** Format: date-time */
            createdAt: string;
        };
        ProviderWithModels: {
            /** Format: uuid */
            id: string;
            baseUrl: string;
            /** Format: date-time */
            createdAt: string;
            models: components["schemas"]["ModelSummary"][];
        };
        ToolCatalogEntry: {
            name: string;
            description: string;
            /** @enum {string} */
            sideEffectLevel: "READ_ONLY" | "WRITE_IDEMPOTENT" | "WRITE_NON_IDEMPOTENT";
        };
        Agent: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            /** @description 系统提示词 */
            instruction: string;
            /** @description 这个 Agent 被允许使用的工具名子集（见 ToolCatalogEntry.name） */
            toolNames: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateAgentRequest: {
            /** @example 计算助手 */
            name: string;
            description?: string;
            /** @example 你是一个帮助用户做算术和资料检索的助手。 */
            instruction?: string;
            /**
             * @example [
             *       "calculator"
             *     ]
             */
            toolNames?: string[];
        };
        StartAgentRunRequest: {
            /** @example 3 个 128 的和乘以 2 是多少？ */
            input: string;
        };
        AgentRun: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            agentId: string;
            /** @enum {string} */
            status: "pending" | "running" | "completed" | "failed" | "cancelled" | "interrupted";
            currentStep: number;
            input: string;
            output: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AgentRunStep: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            runId: string;
            seq: number;
            /** @enum {string} */
            type: "llm" | "tool";
            /** @enum {string} */
            status: "pending" | "running" | "completed" | "failed" | "interrupted";
            toolName?: string | null;
            /** @description 原始 JSON，形状由具体工具决定，前端不需要强类型解析 */
            toolArgs?: unknown;
            toolResult?: unknown;
            latencyMs?: number | null;
            error?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        Problem: {
            /**
             * @description 机器可读的错误类型，前端按它分支
             * @example not_found
             */
            type: string;
            /**
             * @description 人类可读的简短说明
             * @example 资源不存在
             */
            title?: string;
            /** @example 404 */
            status: number;
            /**
             * @description 具体说明
             * @example knowledge base 3f2b1c... not found
             */
            detail?: string;
        };
    };
    responses: {
        /** @description 参数不合法 */
        InvalidArgument: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 资源不存在 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 服务内部错误 */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务正常 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status: string;
                    };
                };
            };
        };
    };
    listKnowledgeBases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 知识库列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBase"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createKnowledgeBase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateKnowledgeBaseRequest"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBase"];
                };
            };
            400: components["responses"]["InvalidArgument"];
            500: components["responses"]["InternalError"];
        };
    };
    getKnowledgeBase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 找到了 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBase"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteKnowledgeBase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删掉了，无返回内容 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["InternalError"];
        };
    };
    renameKnowledgeBase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameKnowledgeBaseRequest"];
            };
        };
        responses: {
            /** @description 改好了，无返回内容 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["InvalidArgument"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 文档列表（按创建时间倒序） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    uploadDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description 已接收，进入处理队列 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            400: components["responses"]["InvalidArgument"];
            500: components["responses"]["InternalError"];
        };
    };
    getDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 找到了 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删掉了，无返回内容 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["InternalError"];
        };
    };
    createConversation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConversationRequest"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            400: components["responses"]["InvalidArgument"];
            500: components["responses"]["InternalError"];
        };
    };
    listConversationMessages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 消息列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    sendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description SSE 流开始。之后的成功/失败都通过流内事件表达 （token/citation/error/done），不再改变这个 200。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["InvalidArgument"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    subscribeConversationEvents: {
        parameters: {
            query?: {
                /** @description 只返回这个 id 之后的事件；省略或传 0 表示从头开始 */
                after_event_id?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE 流（补发历史事件后保持连接，继续推送新事件） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider 列表，每个带它挂着的模型 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderWithModels"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createProvider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProviderRequest"];
            };
        };
        responses: {
            /** @description 探测成功，三行已落库，向量列已建好 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderWithModels"];
                };
            };
            400: components["responses"]["InvalidArgument"];
            500: components["responses"]["InternalError"];
            /** @description 上游模型服务出错（Base URL / Key / 模型名有问题，或探测请求失败） */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listToolCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 工具目录 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolCatalogEntry"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent 列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAgentRequest"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            400: components["responses"]["InvalidArgument"];
            500: components["responses"]["InternalError"];
        };
    };
    getAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent 详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listAgentRuns: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run 列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRun"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    startAgentRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartAgentRunRequest"];
            };
        };
        responses: {
            /** @description SSE 流开始 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["InvalidArgument"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listRunSteps: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Step 列表，按 seq 升序 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunStep"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
}
