/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 存活探针 */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 就绪探针（探测数据库） */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-bases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出全部知识库（按创建时间倒序） */
        get: operations["listKnowledgeBases"];
        put?: never;
        /** 新建一个知识库 */
        post: operations["createKnowledgeBase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-bases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 取一个知识库 */
        get: operations["getKnowledgeBase"];
        put?: never;
        post?: never;
        /** 删除知识库（连带它的文档和分块） */
        delete: operations["deleteKnowledgeBase"];
        options?: never;
        head?: never;
        /** 改知识库的名字 */
        patch: operations["renameKnowledgeBase"];
        trace?: never;
    };
    "/api/v1/knowledge-bases/{id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 列出这个知识库下的文档（按创建时间倒序，keyset 分页） */
        get: operations["listDocuments"];
        put?: never;
        /** 上传一个文档（异步处理：落盘 + 入队，立即返回） */
        post: operations["uploadDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-bases/{id}/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重新索引一个知识库下的全部文档 */
        post: operations["reindexKnowledgeBase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-bases/{id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 在指定知识库里做一次向量检索，返回命中的分块与相似度 */
        post: operations["searchKnowledgeBase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 查一份文档的当前状态（前端拿它做处理中的轮询） */
        get: operations["getDocument"];
        put?: never;
        post?: never;
        /** 删除一份文档（连带它的分块；磁盘文件异步清理） */
        delete: operations["deleteDocument"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{id}/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重新索引一份文档（重新切分、向量化、入库） */
        post: operations["reindexDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 列出会话（keyset 分页），按**最近活动时间**倒序。
         *
         *     【为什么排序键不是 createdAt】这个列表的用处是"回到刚才那个会话"，
         *     而一个三天前建的会话可能刚刚才被用过。按创建时间排会让它沉到列表
         *     底部，用户每次都得往下翻——列表的意义正好没了。
         *
         *     【形状与另外三个列表一致】items + nextCursor，不是裸数组
         *     （v3.0 把三个列表端点统一成了这个形状，新端点跟着走，
         *     否则会出现两种列表形状并存）。
         */
        get: operations["listConversations"];
        put?: never;
        /** 新建一个会话 */
        post: operations["createConversation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 列出一个会话的消息（按 sequence_no 升序，keyset 分页，第一页给最新的） */
        get: operations["listConversationMessages"];
        put?: never;
        /**
         * 发一条消息，响应是 SSE 流（text/event-stream），不是普通 JSON。
         *     帧格式和事件类型见 docs/sse-protocol.md，那份文档是唯一权威来源，
         *     这里的 schema 只是占位（OpenAPI 对流式响应体的描述能力有限）。
         *
         *     带 Idempotency-Key 重复提交时不会重新生成：服务端把那一轮已经
         *     产生的事件补发一遍（同样的 event 类型、同样的真实 event_id），
         *     所以客户端不需要为「重发」写第二套解析逻辑。
         *
         *     补发的作用域是「同一个会话 + 同一个键」。键保留 24 小时，过期之后
         *     同一个键可以重新执行。
         */
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 断线续传入口（SSE），docs/sse-protocol.md「断线续传」一节 */
        get: operations["subscribeConversationEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出已配置的模型接入（Key 不会出现在响应里） */
        get: operations["listProviders"];
        put?: never;
        /** 保存一个模型接入配置（引导页"保存并开始"） */
        post: operations["createProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 按模型聚合的 token 用量 */
        get: operations["getUsageSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出可用工具目录（创建 Agent 表单的勾选列表用） */
        get: operations["listToolCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出已创建的 Agent */
        get: operations["listAgents"];
        put?: never;
        /** 创建一个 Agent */
        post: operations["createAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 查一个 Agent 的配置 */
        get: operations["getAgent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 列出一个 Agent 的历史执行记录（按创建时间倒序，keyset 分页） */
        get: operations["listAgentRuns"];
        put?: never;
        /**
         * 启动一次 Agent 执行，响应是 SSE 流（text/event-stream）——
         *     和 sendMessage 同一个模式,帧格式见 docs/sse-protocol.md。
         *
         *     **流的首帧永远是 `run_started`**（data: {"runId": ...}），
         *     新建与命中幂等键重放两种情况都会发。取消、run 级重订阅、
         *     跳转到运行详情都要用这个 id，而此前五种事件里没有任何一种带它。
         *
         *     带 Idempotency-Key 重复提交时不会重新执行：服务端把那条 run
         *     已记录的事件补发一遍（同样的 event 类型、同样的真实 event_id）。
         *     作用的范围是「同一个 Agent + 同一个键」，键保留 24 小时。
         */
        post: operations["startAgentRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{runId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        /**
         * 补发一条 run 已经记录的事件（run 维度的断线重订阅）。
         *
         *     **补发完已有的历史就结束响应**，不持有连接等新事件——与会话维度那条
         *     GET /conversations/{id}/events 是同一条语义。要看后续内容就再连一次。
         *
         *     `after_event_id` 省略时从 0 开始，也就是把这条 run 的事件从头补发
         *     一遍（run 的事件号从 1 开始，按 run 独立发号）。
         */
        get: operations["subscribeRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{runId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 取消一次在途的 Agent 运行。
         *
         *     取消后 run 的状态是 `cancelled`（不是 `failed`）——两者对用户的含义
         *     完全不同：前者是他自己要求的，后者是出错了。已经跑到终态的 run
         *     不可取消（409 conflict），没跑完的那一步保持 `interrupted`
         *     （取消发生在 run 层，step 没有 cancelled 这一态）。
         *
         *     响应里带的是**取消生效之后**的状态，不是取消前的快照。
         */
        post: operations["cancelAgentRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{runId}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 从断点恢复一次被中断的运行（第二步起）。响应是 SSE 流，
         *     首帧同样是 run_started。
         *
         *     **先检查再开流**：所有拒绝理由都在这条请求变成流之前判掉，
         *     所以下面那三种 409 是正常的 Problem 响应，而不是流里的一帧——
         *     客户端能按 type 给出准确的下一步提示。
         *
         *     拒绝的三种情况：
         *     - `conflict`：只有 interrupted 的 run 可以恢复（别的状态要么已经
         *       结束、要么正在跑）。
         *     - `state_schema_version_mismatch`：这条 run 的快照是旧版本的代码
         *       写的，结构已经不兼容——明确拒绝并提示重新发起，而不是硬解出
         *       一个半截状态。
         *     - `tool_effect_already_applied` / `replay_unsafe`：没跑完的那一步
         *       不允许被平台自动重放（副作用可能已经生效，或工具自己声明了
         *       不可重放）。方案 §8 的恢复边界明说了不保证这类工具被安全重放。
         */
        post: operations["resumeAgentRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{runId}/steps": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        /** 列出一次执行的全部步骤（执行轨迹页用） */
        get: operations["listRunSteps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        KnowledgeBase: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Conversation: {
            /** Format: uuid */
            id: string;
            title: string;
            /**
             * Format: uuid
             * @description 可选关联的知识库——关联了，发消息时会做检索增强；
             *     不关联就是一次不带 RAG 的纯对话。方案文档没有定义这个字段，
             *     是实现时补上的决策（见 internal/conversation/model.go 的注释）。
             */
            knowledgeBaseId?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateConversationRequest: {
            /** @example 关于 ConGoRAG 的问答 */
            title?: string;
            /** Format: uuid */
            knowledgeBaseId?: string | null;
        };
        SendMessageRequest: {
            /** @example ConGoRAG 的默认端口是多少？ */
            text: string;
        };
        Message: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            conversationId: string;
            /** @enum {string} */
            role: "system" | "user" | "assistant" | "tool";
            content: string;
            /** @enum {string} */
            status: "streaming" | "completed" | "failed";
            /** Format: int64 */
            sequenceNo: number;
            /** Format: date-time */
            createdAt: string;
        };
        /**
         * @example {
         *       "query": "ConGoRAG 的向量检索用的是什么类型？",
         *       "topK": 5
         *     }
         */
        KnowledgeSearchRequest: {
            /** @description 要检索的文本。会先被当前生效的 embedding 模型变成向量。 */
            query: string;
            /**
             * @description 最多返回多少个命中分块。省略时用 5。
             *
             *     【越界返回 400，不静默夹取】夹取会让人以为"只命中这么多"，
             *     而实际是被服务端截断了——调试视图上这个区别很关键。
             */
            topK?: number | null;
        };
        KnowledgeSearchHit: {
            /** Format: uuid */
            chunkId: string;
            /** Format: uuid */
            documentId: string;
            /** @description 这个分块来自哪份文档（检索 SQL 里 JOIN documents 拿到） */
            filename: string;
            /** @description 分块正文 */
            snippet: string;
            /**
             * Format: double
             * @description 余弦相似度，越大越相关
             */
            score: number;
        };
        KnowledgeSearchResult: {
            /**
             * @description 按相似度从高到低。可能是空数组（这个知识库没有任何向量，
             *     或者 query 与所有分块都不相关）——空数组与"检索失败"是两件事，
             *     前者前端应显示"没有命中"，后者是一个 4xx/5xx。
             */
            hits: components["schemas"]["KnowledgeSearchHit"][];
        };
        Document: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            knowledgeBaseId: string;
            /** @description 用户上传时的原始文件名 */
            filename: string;
            /**
             * @description 四态状态机（代码架构设计 §5.4）：queued → processing → ready，
             *     任意阶段失败进 failed，failed 只能退回 queued 重试。
             * @enum {string}
             */
            status: "queued" | "processing" | "ready" | "failed";
            /** Format: int64 */
            byteSize: number;
            /**
             * Format: int64
             * @description 这份文档当前的向量分块数（issue #82）。
             *
             *     【为什么它是"检索质量的第一个可观察量"】切分策略不合适时分块数
             *     会明显异常（一份 10 页的 PDF 切出 3 块、或者切出 8000 块）。
             *     它也是"文档到底处理完没有"的第二个信号：status 是 ready 但
             *     chunkCount 是 0，说明切分或向量化那一轮实际上什么都没产出。
             *
             *     未处理完的文档是 0——不是 null。null 会让前端多写一条分支，
             *     而"还没有分块"和"没有这个字段"对用户是同一件事。
             */
            chunkCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ReindexAccepted: {
            /**
             * @description 本次真的排进队列的文档数。已经在排队或正在处理的文档不计入——
             *     它们本来就会被重新处理一遍。
             */
            enqueued: number;
        };
        DocumentPage: {
            items: components["schemas"]["Document"][];
            /** @description 下一页的游标；null 表示没有更多了。 */
            nextCursor?: string | null;
        };
        AgentRunPage: {
            items: components["schemas"]["AgentRun"][];
            /** @description 下一页的游标；null 表示没有更多了。 */
            nextCursor?: string | null;
        };
        ConversationPage: {
            items: components["schemas"]["Conversation"][];
            /** @description 下一页的游标；null 表示没有更多了。 */
            nextCursor?: string | null;
        };
        MessagePage: {
            items: components["schemas"]["Message"][];
            /**
             * @description 下一页的游标；null 表示没有更早的消息了。
             *
             *     **方向是「更旧」**：会话消息的第一页给的是**最新**的 N 条
             *     （按 sequence_no 升序返回），翻下一页拿的是更早的。聊天页
             *     打开就该看到最近发生的事，而不是一年前的那一句。
             */
            nextCursor?: string | null;
        };
        CreateKnowledgeBaseRequest: {
            /** @example 我的知识库 */
            name: string;
        };
        RenameKnowledgeBaseRequest: {
            /** @example 新的名字 */
            name: string;
        };
        /**
         * @description 模型声明支持的能力，全部由用户手动勾选——OpenAI 兼容 API
         *     不保证能自动查询这些（技术方案 §五）。embedding 这一位不在这里：
         *     它由服务端根据这个模型是 chatModel 还是 embeddingModel 自动决定，
         *     不需要用户勾选。
         */
        Capabilities: {
            /** @default true */
            chat: boolean;
            /** @default false */
            streaming: boolean;
            /** @default true */
            toolCalling: boolean;
            /** @default false */
            reasoning: boolean;
        };
        ChatModelInput: {
            /** @example Qwen/Qwen2.5-7B-Instruct */
            modelId: string;
            capabilities?: components["schemas"]["Capabilities"];
            /** @example 32000 */
            contextWindow: number;
            /** @example 4096 */
            maxOutputTokens: number;
            /** @example cl100k_base */
            tokenizerType: string;
        };
        CreateProviderRequest: {
            /** @example https://api.siliconflow.cn/v1 */
            baseUrl: string;
            /** @description 落盘前用应用级主密钥加密，明文只在这一次请求体里出现 */
            apiKey: string;
            chatModel: components["schemas"]["ChatModelInput"];
            /**
             * @description 只要模型名——维度不用填，服务端用这个字段连同 baseUrl/apiKey
             *     发一次真实的 embedding 请求探测出来。
             * @example BAAI/bge-m3
             */
            embeddingModelId: string;
            /**
             * @description 用户已经确认"换 embedding 模型会清空已有向量、并自动重建"。
             *
             *     默认 false：库里的向量不属于这个模型、或者改列类型会清空已有
             *     向量时，保存失败并返回 409 `embedding_change_requires_reindex`，
             *     不做任何修改。前端据此弹确认框，用户点了确认再带 true 重发一次。
             *
             *     true：在同一个事务里清空这些向量、改列类型，并把全部文档重新
             *     排队重建；重建完成的文档数在响应的 requeuedDocuments 里。
             * @default false
             */
            allowEmbeddingReset: boolean;
        };
        ModelSummary: {
            /** Format: uuid */
            id: string;
            modelId: string;
            /** @enum {string} */
            kind: "chat" | "embedding";
            capabilities: components["schemas"]["Capabilities"];
            contextWindow: number;
            maxOutputTokens: number;
            tokenizerType: string;
            /** @description 只对 kind = embedding 有意义；chat 模型这一位恒为 0 */
            embeddingDim: number;
            /** Format: date-time */
            createdAt: string;
        };
        ProviderWithModels: {
            /** Format: uuid */
            id: string;
            baseUrl: string;
            /** Format: date-time */
            createdAt: string;
            models: components["schemas"]["ModelSummary"][];
            /**
             * @description 这一次真的被重新排队的文档数。只有 POST /providers 在确实执行了
             *     重建时才是一个数字；GET /providers 恒为 null——它描述的是"这一次
             *     请求做了什么"，不是一个可以持久化的状态。
             */
            requeuedDocuments?: number | null;
        };
        UsageSummary: {
            /** Format: int64 */
            totalPromptTokens: number;
            /** Format: int64 */
            totalCompletionTokens: number;
            byModel: components["schemas"]["UsageByModel"][];
        };
        UsageByModel: {
            /** Format: uuid */
            providerId: string;
            /**
             * Format: uuid
             * @description llm_models 的主键
             */
            modelId: string;
            /**
             * @description 用户在引导页里敲的那个模型名（llm_models.model_id）。
             *     给用户看的是它，不是上面那个 uuid。
             */
            modelName: string;
            /** @enum {string} */
            kind: "chat" | "embedding";
            /**
             * Format: int64
             * @description 调用次数。**哪怕上游没回 usage 也会计一次**（那一行的 token 记 0）
             *     ——行数代表调用次数，是可观测事实。
             */
            calls: number;
            /** Format: int64 */
            promptTokens: number;
            /** Format: int64 */
            completionTokens: number;
        };
        ToolCatalogEntry: {
            name: string;
            description: string;
            /** @enum {string} */
            sideEffectLevel: "READ_ONLY" | "WRITE_IDEMPOTENT" | "WRITE_NON_IDEMPOTENT";
        };
        Agent: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            /** @description 系统提示词 */
            instruction: string;
            /** @description 这个 Agent 被允许使用的工具名子集（见 ToolCatalogEntry.name） */
            toolNames: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateAgentRequest: {
            /** @example 计算助手 */
            name: string;
            description?: string;
            /** @example 你是一个帮助用户做算术和资料检索的助手。 */
            instruction?: string;
            /**
             * @example [
             *       "calculator"
             *     ]
             */
            toolNames?: string[];
        };
        StartAgentRunRequest: {
            /** @example 3 个 128 的和乘以 2 是多少？ */
            input: string;
        };
        AgentRun: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            agentId: string;
            /** @enum {string} */
            status: "pending" | "running" | "completed" | "failed" | "cancelled" | "interrupted";
            currentStep: number;
            input: string;
            output: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AgentRunStep: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            runId: string;
            seq: number;
            /** @enum {string} */
            type: "llm" | "tool";
            /** @enum {string} */
            status: "pending" | "running" | "completed" | "failed" | "interrupted";
            toolName?: string | null;
            /** @description 原始 JSON，形状由具体工具决定，前端不需要强类型解析 */
            toolArgs?: unknown;
            toolResult?: unknown;
            latencyMs?: number | null;
            error?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        Problem: {
            /**
             * @description 机器可读的错误类型，前端按它分支
             * @example not_found
             */
            type: string;
            /**
             * @description 人类可读的简短说明
             * @example 资源不存在
             */
            title?: string;
            /** @example 404 */
            status: number;
            /**
             * @description 具体说明
             * @example knowledge base 3f2b1c... not found
             */
            detail?: string;
        };
    };
    responses: {
        /** @description 参数不合法 */
        InvalidArgument: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 与已有状态冲突 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description 换 embedding 模型需要先确认清空并重建。
         *     type 是 embedding_change_requires_reindex，detail 里写明会丢掉
         *     多少行、以及怎么继续（带 allowEmbeddingReset 重发）。
         */
        EmbeddingChangeRequiresReindex: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 资源不存在 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 服务内部错误 */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 依赖不可用 */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /**
         * @description 一页最多返回多少条。省略时用 50；允许 1..200，越界返回 400
         *     （不静默夹取——那会让你以为拿满了，实际少了一半）。
         */
        Limit: number;
        /**
         * @description 上一页响应里 nextCursor 的值，用来取下一页。第一页省略它。
         *
         *     **不透明**：不要解析它的内容、也不要自己构造。它的格式（目前是
         *     base64）随时可能变，按内容分支的客户端会在某次升级后静默拿到
         *     错的一页。解不出来时服务端返回 400。
         *
         *     方向：nextCursor 的含义是「更旧的一页」（这三个列表都是按时间
         *     倒序、或按消息序号往回翻），不是「第 N+1 页」。
         */
        Cursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务正常 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status: string;
                    };
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 依赖可用，可以接收流量 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status: string;
                    };
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listKnowledgeBases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 知识库列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBase"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createKnowledgeBase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateKnowledgeBaseRequest"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBase"];
                };
            };
            400: components["responses"]["InvalidArgument"];
            500: components["responses"]["InternalError"];
        };
    };
    getKnowledgeBase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 找到了 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBase"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteKnowledgeBase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删掉了，无返回内容 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["InternalError"];
        };
    };
    renameKnowledgeBase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameKnowledgeBaseRequest"];
            };
        };
        responses: {
            /** @description 改好了，无返回内容 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["InvalidArgument"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listDocuments: {
        parameters: {
            query?: {
                /**
                 * @description 一页最多返回多少条。省略时用 50；允许 1..200，越界返回 400
                 *     （不静默夹取——那会让你以为拿满了，实际少了一半）。
                 */
                limit?: components["parameters"]["Limit"];
                /**
                 * @description 上一页响应里 nextCursor 的值，用来取下一页。第一页省略它。
                 *
                 *     **不透明**：不要解析它的内容、也不要自己构造。它的格式（目前是
                 *     base64）随时可能变，按内容分支的客户端会在某次升级后静默拿到
                 *     错的一页。解不出来时服务端返回 400。
                 *
                 *     方向：nextCursor 的含义是「更旧的一页」（这三个列表都是按时间
                 *     倒序、或按消息序号往回翻），不是「第 N+1 页」。
                 */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 一页文档 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPage"];
                };
            };
            400: components["responses"]["InvalidArgument"];
            500: components["responses"]["InternalError"];
        };
    };
    uploadDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description 已接收，进入处理队列 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            400: components["responses"]["InvalidArgument"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    reindexKnowledgeBase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已排入处理队列 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReindexAccepted"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    searchKnowledgeBase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeSearchRequest"];
            };
        };
        responses: {
            /** @description 命中的分块，按相似度从高到低 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeSearchResult"];
                };
            };
            400: components["responses"]["InvalidArgument"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
            /** @description 上游模型服务出错 */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 找到了 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删掉了，无返回内容 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    reindexDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已排入处理队列 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    listConversations: {
        parameters: {
            query?: {
                /**
                 * @description 一页最多返回多少条。省略时用 50；允许 1..200，越界返回 400
                 *     （不静默夹取——那会让你以为拿满了，实际少了一半）。
                 */
                limit?: components["parameters"]["Limit"];
                /**
                 * @description 上一页响应里 nextCursor 的值，用来取下一页。第一页省略它。
                 *
                 *     **不透明**：不要解析它的内容、也不要自己构造。它的格式（目前是
                 *     base64）随时可能变，按内容分支的客户端会在某次升级后静默拿到
                 *     错的一页。解不出来时服务端返回 400。
                 *
                 *     方向：nextCursor 的含义是「更旧的一页」（这三个列表都是按时间
                 *     倒序、或按消息序号往回翻），不是「第 N+1 页」。
                 */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 一页会话（按最近活动时间倒序） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationPage"];
                };
            };
            400: components["responses"]["InvalidArgument"];
            500: components["responses"]["InternalError"];
        };
    };
    createConversation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConversationRequest"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            400: components["responses"]["InvalidArgument"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listConversationMessages: {
        parameters: {
            query?: {
                /**
                 * @description 一页最多返回多少条。省略时用 50；允许 1..200，越界返回 400
                 *     （不静默夹取——那会让你以为拿满了，实际少了一半）。
                 */
                limit?: components["parameters"]["Limit"];
                /**
                 * @description 上一页响应里 nextCursor 的值，用来取下一页。第一页省略它。
                 *
                 *     **不透明**：不要解析它的内容、也不要自己构造。它的格式（目前是
                 *     base64）随时可能变，按内容分支的客户端会在某次升级后静默拿到
                 *     错的一页。解不出来时服务端返回 400。
                 *
                 *     方向：nextCursor 的含义是「更旧的一页」（这三个列表都是按时间
                 *     倒序、或按消息序号往回翻），不是「第 N+1 页」。
                 */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 一页消息（升序） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePage"];
                };
            };
            400: components["responses"]["InvalidArgument"];
            500: components["responses"]["InternalError"];
        };
    };
    sendMessage: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description 客户端生成的去重键。同一个会话里带同一个键重复提交时，
                 *     服务端不重新执行生成，而是把该轮已记录的事件补发出来，
                 *     并以该轮的 done / error 帧收尾。
                 *
                 *     省略这个头时行为与没有幂等能力时完全一样（每次都重新生成）。
                 *     同一个键配不同的正文会返回 invalid_argument 的错误帧，
                 *     而不是把上一轮的回答重放一遍。
                 */
                "Idempotency-Key"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description SSE 流开始。之后的成功/失败都通过流内事件表达 （token/citation/error/done），不再改变这个 200。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["InvalidArgument"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    subscribeConversationEvents: {
        parameters: {
            query?: {
                /** @description 只返回这个 id 之后的事件；省略或传 0 表示从头开始 */
                after_event_id?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description SSE 流。把 event_id > after_event_id 的事件补发一遍，然后结束响应。
             *     【它不持有连接等新事件】——那条承诺从来没有被实现，本地单机场景
             *     下也没有意义。要看某一轮后续的内容用 POST messages 的幂等键补发
             *     （见 docs/sse-protocol.md「幂等与断线的闭环」）。
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider 列表，每个带它挂着的模型 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderWithModels"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createProvider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProviderRequest"];
            };
        };
        responses: {
            /** @description 探测成功，三行已落库，向量列已建好 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderWithModels"];
                };
            };
            400: components["responses"]["InvalidArgument"];
            409: components["responses"]["EmbeddingChangeRequiresReindex"];
            500: components["responses"]["InternalError"];
            /** @description 上游模型服务出错（Base URL / Key / 模型名有问题，或探测请求失败） */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getUsageSummary: {
        parameters: {
            query?: {
                /** @description 起始时间（含）。RFC3339 格式。省略表示不限。 */
                since?: string;
                /** @description 结束时间（不含）。RFC3339 格式。省略表示不限。 */
                until?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 用量汇总 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageSummary"];
                };
            };
            400: components["responses"]["InvalidArgument"];
            500: components["responses"]["InternalError"];
        };
    };
    listToolCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 工具目录 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolCatalogEntry"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent 列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAgentRequest"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            400: components["responses"]["InvalidArgument"];
            500: components["responses"]["InternalError"];
        };
    };
    getAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent 详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listAgentRuns: {
        parameters: {
            query?: {
                /**
                 * @description 一页最多返回多少条。省略时用 50；允许 1..200，越界返回 400
                 *     （不静默夹取——那会让你以为拿满了，实际少了一半）。
                 */
                limit?: components["parameters"]["Limit"];
                /**
                 * @description 上一页响应里 nextCursor 的值，用来取下一页。第一页省略它。
                 *
                 *     **不透明**：不要解析它的内容、也不要自己构造。它的格式（目前是
                 *     base64）随时可能变，按内容分支的客户端会在某次升级后静默拿到
                 *     错的一页。解不出来时服务端返回 400。
                 *
                 *     方向：nextCursor 的含义是「更旧的一页」（这三个列表都是按时间
                 *     倒序、或按消息序号往回翻），不是「第 N+1 页」。
                 */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 一页运行记录 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunPage"];
                };
            };
            400: components["responses"]["InvalidArgument"];
            500: components["responses"]["InternalError"];
        };
    };
    startAgentRun: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description 客户端生成的去重键。同一个 Agent 上带同一个键重复提交时，
                 *     服务端不重新执行这次运行，而是把该 run 已记录的事件补发出来
                 *     （首帧仍是 run_started，带的是原来那条 run 的 id）。
                 *
                 *     省略这个头时行为与没有幂等能力时完全一样（每次都真正执行）。
                 *     同一个键配不同的 input 会返回 invalid_argument 的错误帧，
                 *     而不是把上一次运行的结果重放一遍。
                 *
                 *     保留窗口与会话消息那条路径共用同一个值（24 小时，见
                 *     docs/adr/008-idempotency-replay-window.md）。过期之后同一个键
                 *     可以重新执行——这是有意的产品语义，不是缺陷。
                 */
                "Idempotency-Key"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartAgentRunRequest"];
            };
        };
        responses: {
            /** @description SSE 流开始 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["InvalidArgument"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    subscribeRunEvents: {
        parameters: {
            query?: {
                /** @description 只补发 event_id 严格大于它的那些事件。 */
                after_event_id?: number;
            };
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE 流（补发完即结束） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    cancelAgentRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取消后的运行记录 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRun"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    resumeAgentRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE 流开始 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    listRunSteps: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Step 列表，按 seq 升序 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunStep"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
}
